modLoader="javafml"
loaderVersion="${loader_version_range}"
license="AGPL-3.0-only"
issueTrackerURL="https://github.com/Alexkist/Server-Eye/issues"

[[mods]]

modId="${mod_id}"
displayName="${mod_name}"
version="${mod_version}"

authors="${mod_authors}"
credits="Alexkist, Febreeze, Zaid"
description='''${mod_description}'''

# displayURL="https://modrinth.com/mod/server-eye"
logoFile="icon.jpg"

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"